name: Rust

on:
  workflow_dispatch:
  

env:
  CARGO_TERM_COLOR: always


jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo install -q worker-build && worker-build --release
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: wisp-server-built
        path: .
